const ActionTypes = {
    FETCH_PRODUCTS_BEGIN: "FETCH_PRODUCTS_BEGIN",
    FETCH_PRODUCTS_SUCCESS: "FETCH_PRODUCTS_SUCCESS",
    FETCH_PRODUCTS_ERROR: "FETCH_PRODUCTS_ERROR"
}

export default ActionTypes;